# name: smart_home_application
# description: "A new Flutter project."
# # The following line prevents the package from being accidentally published to
# # pub.dev using `flutter pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# # The following defines the version and build number for your application.
# # A version number is three numbers separated by dots, like 1.2.43
# # followed by an optional build number separated by a +.
# # Both the version and the builder number may be overridden in flutter
# # build by specifying --build-name and --build-number, respectively.
# # In Android, build-name is used as versionName while build-number used as versionCode.
# # Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# # In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# # Read more about iOS versioning at
# # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# # In Windows, build-name is used as the major, minor, and patch parts
# # of the product and file versions while build-number is used as the build suffix.
# version: 1.0.0+1

# environment:
#   sdk: ^3.5.3

# # Dependencies specify other packages that your package needs in order to work.
# # To automatically upgrade your package dependencies to the latest versions
# # consider running `flutter pub upgrade --major-versions`. Alternatively,
# # dependencies can be manually updated by changing the version numbers below to
# # the latest version available on pub.dev. To see which dependencies have newer
# # versions available, run `flutter pub outdated`.
# dependencies:
#   flutter:
#     sdk: flutter


#   # The following adds the Cupertino Icons font to your application.
#   # Use with the CupertinoIcons class for iOS style icons.
#   cupertino_icons: ^1.0.8
 
#   syncfusion_flutter_charts: ^20.1.55
#   firebase_core: ^3.6.0
#   # firebase_auth: ^6.15.0  
#   firebase_auth: ^5.3.1
#   google_fonts: ^6.2.1
#   provider: ^6.1.2
#   flutter_colorpicker: ^1.0.0
#   cloud_firestore: ^5.4.4
#   file_picker: ^8.1.2              # Updated to latest version
#   fl_chart: ^0.69.0                # Updated to latest version
#   # flutter_ringtone_player: ^4.0.0+3
#   syncfusion_flutter_core: ^20.4.54
#   flutter_lints: ^5.0.0  
#   font_awesome_flutter: ^10.7.0
#   speech_to_text: ^7.0.0
#   torch_light: ^1.1.0
#   permission_handler: ^11.3.1
#   logger: ^2.0.0
 
  
  
#    # Updated to latest version
#    # Updated to latest version

# dev_dependencies:
#   flutter_lints: ^5.0.0            # Updated to latest version

# # Transitive dependencies that may need to be manually updated in the `dependency_overrides` section
  
  

# # dev_dependencies:
# #   flutter_test:
# #     sdk: flutter

#   # The "flutter_lints" package below contains a set of recommended lints to
#   # encourage good coding practices. The lint set provided by the package is
#   # activated in the `analysis_options.yaml` file located at the root of your
#   # package. See that file for information about deactivating specific lint
#   # rules and activating additional ones.
#   # flutter_lints: ^5.0.0

# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter packages.
# flutter:

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true

#   # To add assets to your application, add an assets section, like this:
# assets:
#   - sounds/alarm_tone_1.mp3
#   - sounds/alarm_tone_2.mp3
#   - sounds/alarm_tone_3.mp3
#   #   - images/a_dot_burr.jpeg
#   #   - images/a_dot_ham.jpeg

#   # An image asset can refer to one or more resolution-specific "variants", see
#   # https://flutter.dev/to/resolution-aware-images

#   # For details regarding adding assets from package dependencies, see
#   # https://flutter.dev/to/asset-from-package

#   # To add custom fonts to your application, add a fonts section here,
#   # in this "flutter" section. Each entry in this list should have a
#   # "family" key with the font family name, and a "fonts" key with a
#   # list giving the asset and other descriptors for the font. For
#   # example:
#   # fonts:
#   #   - family: Schyler
#   #     fonts:
#   #       - asset: fonts/Schyler-Regular.ttf
#   #       - asset: fonts/Schyler-Italic.ttf
#   #         style: italic
#   #   - family: Trajan Pro
#   #     fonts:
#   #       - asset: fonts/TrajanPro.ttf
#   #       - asset: fonts/TrajanPro_Bold.ttf
#   #         weight: 700
#   #
#   # For details regarding fonts from package dependencies,
#   # see https://flutter.dev/to/font-from-package


name: smart_home_application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  syncfusion_flutter_charts: ^27.1.53  # Updated to the latest version
  firebase_core: ^3.5.0                 # Downgraded to a compatible version
  firebase_auth: ^5.2.0                 # Downgraded to a compatible version
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_colorpicker: ^1.0.0
  cloud_firestore: ^5.4.0                # Downgraded to the latest compatible version
  file_picker: ^8.1.2                   # Updated to the latest version
  fl_chart: ^0.69.0                     # Updated to the latest version
  syncfusion_flutter_core: ^27.1.53      # Updated to the latest version
  flutter_lints: ^2.0.0                  # Use a compatible version
  font_awesome_flutter: ^10.7.0
  speech_to_text: ^7.0.0
  torch_light: ^1.1.0
  permission_handler: ^11.3.1
  logger: ^2.0.0
  # android_alarm_manager_plus: ^4.0.4
  flutter_local_notifications: ^17.2.3
  android_alarm_manager_plus: ^4.0.4
  # flutter_ringtone_player: ^4.0.0+3


  # Removed leak_tracker dependencies to avoid version conflicts
  # collection: ^1.18.0                  # Use the version compatible with Flutter
  # http_parser: ^4.0.2                  # Compatible version
  # leak_tracker: ^10.0.7
  # leak_tracker_flutter_testing: ^3.0.8
  # material_color_utilities: ^0.11.1     # Set to the version required by Flutter
  # meta: ^1.15.0                        # Set to the version required by Flutter
  # process: ^5.0.2

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.0                # Updated to a compatible version

flutter:
  uses-material-design: true

assets:
  - sounds/alarm_tone_1.mp3
  - sounds/alarm_tone_2.mp3
  - sounds/alarm_tone_3.mp3
